apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: mpi-operator
commonLabels:
  kustomize.component: mpi-operator
  app: mpi-operator
  app.kubernetes.io/name: mpi-operator
  app.kubernetes.io/component: mpijob
images:
- name: qwerty1802/mpi-operator
  newName: qwerty1802/mpi-operator
  newTag: latest
configMapGenerator:
- name: mpi-operator-config
  envs:
  - params.env
  behavior: merge
